import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@mui/material/styles';
import theme from 'src/theme';

export const metadata: Metadata = {
  title: 'HackUTD Project',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className="bg-background p-4 text-foreground">{children}</body>
      </ThemeProvider>
    </html>
  );
}
